insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (1, 'Don', 'Atherley', 'datherley0@ca.gov', 'Male', 'not delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (2, 'Arlyn', 'Jaze', 'ajaze1@blogger.com', 'Female', 'delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (3, 'Roldan', 'Normand', 'rnormand2@cdbaby.com', 'Male', 'not delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (4, 'Dallas', 'Jell', 'djell3@businesswire.com', 'Female', 'pending');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (5, 'Barney', 'Stringman', 'bstringman4@barnesandnoble.com', 'Male', 'not delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (6, 'Trace', 'Midlane', 'tmidlane5@cmu.edu', 'Male', 'delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (7, 'Lynett', 'Paler', 'lpaler6@techcrunch.com', 'Female', 'delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (8, 'Ardine', 'Tripett', 'atripett7@oracle.com', 'Female', 'not delivered');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (9, 'Concettina', 'Bolt', 'cbolt8@yellowpages.com', 'Female', 'pending');
insert into MOCK_DATA (id, first_name, last_name, email, gender, ip_address) values (10, 'Orel', 'Ruse', 'oruse9@about.me', 'Female', 'delivered');
