insert into products (product_id, product_name, description, product_category, unit_price) values (1, 'Dark Angel: Ascent, The', 'Open-architected attitude-oriented success', 'Horror|Romance', 10.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (2, 'Black Widow', 'Enhanced bi-directional instruction set', 'Crime|Drama|Mystery|Thriller', 6.08);
insert into products (product_id, product_name, description, product_category, unit_price) values (3, 'Charlie and the Chocolate Factory', 'Robust object-oriented software', 'Adventure|Children|Comedy|Fantasy|IMAX', 9.05);
insert into products (product_id, product_name, description, product_category, unit_price) values (4, 'Broadway Idiot', 'Cross-platform 3rd generation info-mediaries', 'Documentary|Musical', 5.51);
insert into products (product_id, product_name, description, product_category, unit_price) values (5, 'Kicked in the Head', 'Multi-tiered content-based open architecture', 'Comedy|Drama', 7.45);
insert into products (product_id, product_name, description, product_category, unit_price) values (6, 'Live from Baghdad', 'Mandatory fault-tolerant projection', 'Drama|War', 7.4);
insert into products (product_id, product_name, description, product_category, unit_price) values (7, 'Whip and the Body, The (Frusta e il corpo, La)', 'Automated background matrices', 'Horror', 5.96);
insert into products (product_id, product_name, description, product_category, unit_price) values (8, 'Naked Gun 33 1/3: The Final Insult', 'User-friendly stable productivity', 'Action|Comedy', 6.2);
insert into products (product_id, product_name, description, product_category, unit_price) values (9, 'Love Me Tonight', 'Operative disintermediate alliance', 'Comedy|Musical', 10.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (10, 'Corto Maltese in Siberia (Corto Maltese - La cour secrète des Arcanes)', 'Synergistic background customer loyalty', 'Adventure|Animation|Drama|Romance|War', 14.39);
insert into products (product_id, product_name, description, product_category, unit_price) values (11, 'Barcelona', 'User-centric methodical forecast', 'Comedy|Romance', 13.99);
insert into products (product_id, product_name, description, product_category, unit_price) values (12, 'A Life in Dirty Movies', 'Future-proofed 6th generation synergy', 'Documentary', 10.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (13, 'This Is 40', 'Fundamental optimal access', 'Drama', 9.91);
insert into products (product_id, product_name, description, product_category, unit_price) values (14, 'Rocket Science', 'Advanced encompassing challenge', 'Comedy|Drama', 5.25);
insert into products (product_id, product_name, description, product_category, unit_price) values (15, 'As Tears Go By (Wong gok ka moon)', 'Profound secondary neural-net', 'Crime|Drama', 9.37);
insert into products (product_id, product_name, description, product_category, unit_price) values (16, 'Mean Girls 2', 'Mandatory 4th generation adapter', 'Comedy', 7.24);
insert into products (product_id, product_name, description, product_category, unit_price) values (17, 'Photographer (Fotoamator)', 'Cross-group zero administration frame', 'Documentary', 12.23);
insert into products (product_id, product_name, description, product_category, unit_price) values (18, 'The Man Who Lived Again', 'Organized transitional capacity', 'Horror|Sci-Fi', 12.41);
insert into products (product_id, product_name, description, product_category, unit_price) values (19, 'Prince of Persia: The Sands of Time', 'Managed real-time knowledge base', 'Action|Adventure|Fantasy|Romance|IMAX', 11.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (20, 'About Face: Supermodels Then and Now', 'Innovative intangible knowledge base', 'Comedy|Documentary', 7.41);
insert into products (product_id, product_name, description, product_category, unit_price) values (21, 'In the Name of the Father', 'User-friendly attitude-oriented hub', 'Drama', 9.06);
insert into products (product_id, product_name, description, product_category, unit_price) values (22, 'Caramel (Sukkar banat)', 'Proactive dynamic pricing structure', 'Comedy', 10.1);
insert into products (product_id, product_name, description, product_category, unit_price) values (23, 'Rulers of the City', 'Inverse logistical methodology', 'Action|Comedy|Crime', 8.29);
insert into products (product_id, product_name, description, product_category, unit_price) values (24, 'Brothers O''Toole, The', 'Cross-group user-facing support', 'Comedy|Western', 8.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (25, 'The Dancer', 'User-centric real-time intranet', 'Drama|Romance', 6.87);
insert into products (product_id, product_name, description, product_category, unit_price) values (26, 'Bronson', 'Face to face solution-oriented methodology', 'Action|Comedy|Drama|Thriller', 14.49);
insert into products (product_id, product_name, description, product_category, unit_price) values (27, 'Night Crossing', 'Secured content-based function', 'Drama', 9.89);
insert into products (product_id, product_name, description, product_category, unit_price) values (28, 'Some Kind of Hero', 'Persistent foreground task-force', 'Comedy|Drama', 6.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (29, 'Report, The (Gozaresh)', 'Streamlined content-based policy', 'Drama', 7.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (30, 'In the Mood For Love (Fa yeung nin wa)', 'Fundamental global approach', 'Drama|Romance', 10.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (31, 'Face', 'Business-focused scalable task-force', 'Comedy', 11.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (32, 'Holiday Inn', 'Horizontal radical model', 'Comedy|Musical', 9.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (33, 'Fall of the Republic: The Presidency of Barack H. Obama', 'Assimilated fresh-thinking analyzer', 'Documentary', 14.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (34, 'Che: Part Two', 'Public-key holistic knowledge user', 'Drama|War', 7.03);
insert into products (product_id, product_name, description, product_category, unit_price) values (35, 'Twilight Zone: The Movie', 'Devolved local database', 'Fantasy|Horror|Sci-Fi|Thriller', 11.26);
insert into products (product_id, product_name, description, product_category, unit_price) values (36, 'Stag', 'Implemented multimedia utilisation', 'Action|Thriller', 8.73);
insert into products (product_id, product_name, description, product_category, unit_price) values (37, 'Blue Steel', 'Centralized clear-thinking Graphical User Interface', 'Action|Thriller', 14.23);
insert into products (product_id, product_name, description, product_category, unit_price) values (38, 'Alex Cross', 'Re-contextualized full-range project', 'Action|Crime|Mystery|Thriller', 12.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (39, 'Escort, The (Scorta, La)', 'Synergized well-modulated data-warehouse', 'Crime|Thriller', 5.29);
insert into products (product_id, product_name, description, product_category, unit_price) values (40, 'Godfather: Part II, The', 'Adaptive full-range projection', 'Crime|Drama', 14.77);
insert into products (product_id, product_name, description, product_category, unit_price) values (41, 'So It Goes (Korsoteoria)', 'Versatile directional toolset', 'Drama', 9.88);
insert into products (product_id, product_name, description, product_category, unit_price) values (42, 'Flying Home', 'Customizable 24/7 monitoring', 'Romance', 6.26);
insert into products (product_id, product_name, description, product_category, unit_price) values (43, '7500', 'Business-focused content-based artificial intelligence', 'Action|Horror|Mystery|Thriller', 10.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (44, 'Sabretooth', 'Pre-emptive didactic concept', 'Action|Adventure|Horror|Sci-Fi|Thriller', 7.78);
insert into products (product_id, product_name, description, product_category, unit_price) values (45, 'Merchants of Doubt', 'Vision-oriented dedicated utilisation', 'Documentary', 8.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (46, 'World War Z', 'Right-sized motivating conglomeration', 'Action|Drama|Horror|IMAX', 12.97);
insert into products (product_id, product_name, description, product_category, unit_price) values (47, 'First a Girl', 'Organized asynchronous intranet', 'Comedy|Musical', 13.43);
insert into products (product_id, product_name, description, product_category, unit_price) values (48, 'Cold Prey (Fritt Vilt)', 'Multi-channelled encompassing contingency', 'Action|Horror|Mystery|Thriller', 5.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (49, 'Zhou Yu''s Train (Zhou Yu de huo che)', 'Multi-tiered uniform orchestration', 'Drama|Romance', 14.88);
insert into products (product_id, product_name, description, product_category, unit_price) values (50, 'Christopher Strong', 'Managed even-keeled pricing structure', 'Drama', 9.89);
insert into products (product_id, product_name, description, product_category, unit_price) values (51, 'We''ll Never Have Paris', 'Open-architected bifurcated customer loyalty', 'Comedy|Romance', 8.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (52, 'Legally Blonde', 'Stand-alone discrete model', 'Comedy|Romance', 12.67);
insert into products (product_id, product_name, description, product_category, unit_price) values (53, 'Central Park Five, The', 'Balanced interactive neural-net', 'Documentary', 8.02);
insert into products (product_id, product_name, description, product_category, unit_price) values (54, 'Free the Nipple', 'Upgradable asymmetric knowledge base', 'Comedy|Drama', 10.96);
insert into products (product_id, product_name, description, product_category, unit_price) values (55, 'Love Meetings (Comizi d''amore)', 'Centralized mission-critical synergy', 'Documentary', 6.25);
insert into products (product_id, product_name, description, product_category, unit_price) values (56, 'Honeymoon in Vegas', 'Front-line 4th generation solution', 'Comedy|Romance', 12.55);
insert into products (product_id, product_name, description, product_category, unit_price) values (57, 'Count Dracula (Nachts, wenn Dracula erwacht)', 'Re-engineered non-volatile hub', 'Horror|Mystery', 7.17);
insert into products (product_id, product_name, description, product_category, unit_price) values (58, 'Looker', 'Self-enabling client-server strategy', 'Drama|Horror|Sci-Fi|Thriller', 10.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (59, 'Puppet Master 5: The Final Chapter', 'Customizable neutral task-force', 'Horror|Sci-Fi|Thriller', 5.78);
insert into products (product_id, product_name, description, product_category, unit_price) values (60, 'Perfect Game, The', 'Optimized systemic access', 'Drama', 7.46);
insert into products (product_id, product_name, description, product_category, unit_price) values (61, '50 First Dates', 'Public-key disintermediate Graphic Interface', 'Comedy|Romance', 12.01);
insert into products (product_id, product_name, description, product_category, unit_price) values (62, 'Beyond the Law (Lain ulkopuolella)', 'Organic high-level process improvement', 'Crime|Drama|Thriller', 14.64);
insert into products (product_id, product_name, description, product_category, unit_price) values (63, 'Ip Man 2', 'Total 24/7 algorithm', 'Action', 9.87);
insert into products (product_id, product_name, description, product_category, unit_price) values (64, 'Bug', 'Reactive 24/7 alliance', 'Drama|Horror|Thriller', 7.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (65, 'Eva (a.k.a. Eve)', 'Versatile zero administration service-desk', 'Drama', 11.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (66, 'Crime and Punishment', 'Focused logistical orchestration', 'Drama', 5.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (67, 'Big Picture, The', 'Cross-platform zero defect task-force', 'Comedy|Drama', 5.37);
insert into products (product_id, product_name, description, product_category, unit_price) values (68, 'Hireling, The', 'Synergized intermediate emulation', 'Drama', 8.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (69, 'Wrong Turn 2: Dead End', 'Fundamental cohesive moderator', 'Action|Horror|Thriller', 13.42);
insert into products (product_id, product_name, description, product_category, unit_price) values (70, 'And God Created Woman', 'Extended next generation attitude', 'Comedy|Drama|Romance', 7.52);
insert into products (product_id, product_name, description, product_category, unit_price) values (71, 'Raising Arizona', 'Assimilated tertiary matrices', 'Comedy', 5.11);
insert into products (product_id, product_name, description, product_category, unit_price) values (72, 'It Happened Here', 'Ameliorated zero defect alliance', 'Drama|Fantasy|War', 8.23);
insert into products (product_id, product_name, description, product_category, unit_price) values (73, 'One Tough Cop', 'Streamlined web-enabled help-desk', 'Action|Crime', 6.85);
insert into products (product_id, product_name, description, product_category, unit_price) values (74, 'Magic', 'Ameliorated clear-thinking workforce', 'Drama|Horror|Romance|Thriller', 13.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (75, 'Oversimplification of Her Beauty, An', 'Synchronised multimedia database', 'Animation|Comedy|Drama|Romance', 7.83);
insert into products (product_id, product_name, description, product_category, unit_price) values (76, 'Mistaken for Strangers', 'Seamless well-modulated concept', 'Comedy|Documentary', 7.94);
insert into products (product_id, product_name, description, product_category, unit_price) values (77, 'Onibi: The Fire Within', 'Exclusive analyzing solution', 'Drama|Thriller', 5.42);
insert into products (product_id, product_name, description, product_category, unit_price) values (78, 'Tetsuo, the Ironman (Tetsuo)', 'Centralized incremental pricing structure', 'Action|Horror|Sci-Fi|Thriller', 7.31);
insert into products (product_id, product_name, description, product_category, unit_price) values (79, 'Masterminds', 'Total coherent policy', 'Action|Comedy|Thriller', 14.99);
insert into products (product_id, product_name, description, product_category, unit_price) values (80, 'House by the Cemetery, The (Quella villa accanto al cimitero)', 'Enterprise-wide intermediate flexibility', 'Horror', 11.4);
insert into products (product_id, product_name, description, product_category, unit_price) values (81, 'Volver', 'Horizontal uniform success', 'Comedy|Drama', 10.15);
insert into products (product_id, product_name, description, product_category, unit_price) values (82, 'Maybe, Maybe Not (Bewegte Mann, Der)', 'Devolved foreground workforce', 'Comedy', 5.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (83, 'Two Lovers', 'Synergized tangible challenge', 'Drama|Romance', 8.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (84, 'Bent', 'Automated web-enabled info-mediaries', 'Drama|War', 14.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (85, 'Scarecrow', 'Pre-emptive cohesive application', 'Drama', 11.35);
insert into products (product_id, product_name, description, product_category, unit_price) values (86, 'Anatahan', 'Progressive asymmetric emulation', 'Drama|War', 14.23);
insert into products (product_id, product_name, description, product_category, unit_price) values (87, 'The Party', 'Cross-group regional product', 'Drama', 11.16);
insert into products (product_id, product_name, description, product_category, unit_price) values (88, 'FLCL', 'Total 5th generation leverage', 'Animation|Comedy|Fantasy|Sci-Fi', 9.26);
insert into products (product_id, product_name, description, product_category, unit_price) values (89, 'My Blueberry Nights', 'Multi-tiered bottom-line paradigm', 'Drama|Romance', 9.52);
insert into products (product_id, product_name, description, product_category, unit_price) values (90, 'Phase 7', 'Exclusive web-enabled open architecture', 'Comedy|Sci-Fi|Thriller', 5.63);
insert into products (product_id, product_name, description, product_category, unit_price) values (91, 'Giger''s Necronomicon', 'Front-line discrete challenge', 'Documentary', 8.5);
insert into products (product_id, product_name, description, product_category, unit_price) values (92, 'Happy End', 'Customer-focused client-server projection', 'Comedy', 14.19);
insert into products (product_id, product_name, description, product_category, unit_price) values (93, 'Love That Boy', 'Inverse radical synergy', 'Comedy|Romance', 5.64);
insert into products (product_id, product_name, description, product_category, unit_price) values (94, 'Night Crossing', 'Switchable 4th generation help-desk', 'Drama', 7.14);
insert into products (product_id, product_name, description, product_category, unit_price) values (95, 'One Good Cop', 'Cross-platform logistical methodology', 'Action|Crime|Drama', 9.28);
insert into products (product_id, product_name, description, product_category, unit_price) values (96, 'Pride of the Yankees, The', 'Decentralized high-level projection', 'Drama', 13.48);
insert into products (product_id, product_name, description, product_category, unit_price) values (97, 'The Adventure of Faustus Bidgood', 'Team-oriented multimedia toolset', 'Comedy', 5.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (98, 'Holiday Wishes', 'Quality-focused regional architecture', 'Children|Comedy|Drama', 11.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (99, 'My Life in Ruins', 'Reduced composite neural-net', 'Comedy', 7.97);
insert into products (product_id, product_name, description, product_category, unit_price) values (100, 'Tora-san Our Lovable Tramp (Otoko wa tsurai yo)', 'Enhanced mobile knowledge user', 'Comedy|Drama|Romance', 12.03);
insert into products (product_id, product_name, description, product_category, unit_price) values (101, 'Phantom, The', 'Re-engineered non-volatile adapter', 'Action|Adventure', 5.88);
insert into products (product_id, product_name, description, product_category, unit_price) values (102, 'Death King, The (Der Todesking)', 'Synergistic bi-directional circuit', 'Drama|Horror', 12.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (103, 'Braveheart', 'Switchable analyzing utilisation', 'Action|Drama|War', 13.31);
insert into products (product_id, product_name, description, product_category, unit_price) values (104, 'How Tasty Was My Little Frenchman (Como Era Gostoso o Meu Francês)', 'Managed clear-thinking hardware', 'Comedy|Drama', 14.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (105, 'How to Survive a Plague', 'Programmable national emulation', 'Documentary', 12.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (106, 'Morgan Pålsson - världsreporter', 'Adaptive heuristic service-desk', 'Action|Comedy', 11.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (107, 'Last Exit to Brooklyn', 'Devolved explicit workforce', 'Drama', 5.86);
insert into products (product_id, product_name, description, product_category, unit_price) values (108, 'M*A*S*H (a.k.a. MASH)', 'Reactive content-based orchestration', 'Comedy|Drama|War', 7.91);
insert into products (product_id, product_name, description, product_category, unit_price) values (109, 'Garden, The', 'Diverse asynchronous circuit', 'Drama', 5.01);
insert into products (product_id, product_name, description, product_category, unit_price) values (110, 'Girl with the Dragon Tattoo, The', 'Programmable cohesive hub', 'Drama|Thriller', 6.88);
insert into products (product_id, product_name, description, product_category, unit_price) values (111, 'Just Add Water', 'Customizable value-added structure', 'Comedy|Romance', 7.86);
insert into products (product_id, product_name, description, product_category, unit_price) values (112, 'Nine Ways to Approach Helsinki (Yhdeksän tapaa lähestyä Helsinkiä)', 'Switchable fresh-thinking paradigm', 'Documentary', 9.4);
insert into products (product_id, product_name, description, product_category, unit_price) values (113, 'Men in the City (Männerherzen)', 'Virtual directional superstructure', 'Comedy', 7.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (114, 'Color of Pomegranates, The (Sayat Nova)', 'Fully-configurable logistical moratorium', 'Drama', 10.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (115, 'Me tulemme taas', 'Extended bottom-line secured line', 'Comedy|Musical', 7.35);
insert into products (product_id, product_name, description, product_category, unit_price) values (116, 'Attack of the 50ft Cheerleader', 'Self-enabling fresh-thinking model', 'Comedy', 14.49);
insert into products (product_id, product_name, description, product_category, unit_price) values (117, 'Hebrew Hammer, The', 'Upgradable holistic challenge', 'Comedy', 5.53);
insert into products (product_id, product_name, description, product_category, unit_price) values (118, 'City on Fire (Lung fu fong wan)', 'Up-sized bifurcated challenge', 'Action|Crime|Drama|Thriller', 12.02);
insert into products (product_id, product_name, description, product_category, unit_price) values (119, 'Going to Kansas City', 'Inverse system-worthy project', 'Drama|Romance|Thriller', 14.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (120, 'Wet Hot American Summer', 'Front-line bi-directional framework', 'Comedy', 6.26);
insert into products (product_id, product_name, description, product_category, unit_price) values (121, 'Escort, The (Scorta, La)', 'Polarised systematic secured line', 'Crime|Thriller', 9.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (122, 'The Inner Circle', 'Innovative 3rd generation ability', 'Drama', 9.22);
insert into products (product_id, product_name, description, product_category, unit_price) values (123, 'Siberian Education (Educazione siberiana)', 'User-centric homogeneous time-frame', 'Drama', 14.75);
insert into products (product_id, product_name, description, product_category, unit_price) values (124, 'London', 'Open-architected exuding secured line', 'Drama', 14.34);
insert into products (product_id, product_name, description, product_category, unit_price) values (125, 'Route 666', 'Implemented 6th generation array', 'Action|Horror|Thriller', 13.26);
insert into products (product_id, product_name, description, product_category, unit_price) values (126, 'Mysterious Skin', 'Upgradable high-level product', 'Drama|Mystery', 10.29);
insert into products (product_id, product_name, description, product_category, unit_price) values (127, 'Holy Flying Circus', 'Streamlined 5th generation encryption', 'Comedy|Drama', 14.77);
insert into products (product_id, product_name, description, product_category, unit_price) values (128, 'Night Train To Lisbon', 'Customizable static task-force', 'Mystery|Romance|Thriller', 13.95);
insert into products (product_id, product_name, description, product_category, unit_price) values (129, 'Closing the Ring', 'User-centric empowering internet solution', 'Drama|Romance', 13.81);
insert into products (product_id, product_name, description, product_category, unit_price) values (130, 'Dorado, El', 'Devolved regional open architecture', 'Drama', 6.63);
insert into products (product_id, product_name, description, product_category, unit_price) values (131, 'Pocketful of Miracles', 'Pre-emptive motivating hub', 'Comedy|Drama', 9.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (132, 'Gretchen the Greenhorn', 'Face to face content-based moratorium', 'Crime|Drama|Romance', 11.39);
insert into products (product_id, product_name, description, product_category, unit_price) values (133, 'Forger, The', 'Down-sized neutral intranet', 'Drama', 6.76);
insert into products (product_id, product_name, description, product_category, unit_price) values (134, 'Soviet Story, The', 'Enterprise-wide reciprocal instruction set', 'Documentary', 12.88);
insert into products (product_id, product_name, description, product_category, unit_price) values (135, 'Angel''s Leap', 'Future-proofed next generation utilisation', 'Crime', 10.44);
insert into products (product_id, product_name, description, product_category, unit_price) values (136, 'Return of Don Camillo, The (Retour de Don Camillo, Le)', 'Cloned didactic matrix', 'Comedy', 5.67);
insert into products (product_id, product_name, description, product_category, unit_price) values (137, 'Invincible', 'Integrated even-keeled process improvement', 'Drama', 14.49);
insert into products (product_id, product_name, description, product_category, unit_price) values (138, 'Get Rich or Die Tryin''', 'Profit-focused dynamic moderator', 'Action|Crime|Drama', 7.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (139, 'Young Tom Edison', 'Right-sized non-volatile service-desk', 'Drama', 11.88);
insert into products (product_id, product_name, description, product_category, unit_price) values (140, 'Calloused Hands', 'Face to face client-driven emulation', 'Drama', 8.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (141, 'Angel''s Leap', 'Multi-tiered clear-thinking instruction set', 'Crime', 5.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (142, 'Letter for the King, The (Brief voor de koning, De)', 'Optimized cohesive capability', 'Adventure', 11.94);
insert into products (product_id, product_name, description, product_category, unit_price) values (143, 'Is It Easy to be Young?', 'Enhanced 6th generation project', 'Documentary|Drama', 14.72);
insert into products (product_id, product_name, description, product_category, unit_price) values (144, 'BBOY for LIFE', 'Re-engineered tangible solution', 'Adventure|Crime|Documentary|Drama', 5.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (145, 'Joan of Paris', 'Sharable reciprocal flexibility', 'Drama|Romance|War', 13.72);
insert into products (product_id, product_name, description, product_category, unit_price) values (146, 'Bird on a Wire', 'Universal static help-desk', 'Action|Comedy|Romance', 10.19);
insert into products (product_id, product_name, description, product_category, unit_price) values (147, 'We''re the Millers', 'Horizontal bi-directional task-force', 'Comedy|Crime', 6.45);
insert into products (product_id, product_name, description, product_category, unit_price) values (148, 'Retro Puppet Master (Puppet Master 7)', 'Synergized neutral concept', 'Horror|Sci-Fi|Thriller', 5.16);
insert into products (product_id, product_name, description, product_category, unit_price) values (149, 'The Voices', 'Persistent systematic parallelism', 'Comedy|Crime|Thriller', 10.16);
insert into products (product_id, product_name, description, product_category, unit_price) values (150, 'Dial M for Murder', 'Re-engineered maximized definition', 'Crime|Mystery|Thriller', 14.59);
insert into products (product_id, product_name, description, product_category, unit_price) values (151, 'Mr. Untouchable', 'Vision-oriented non-volatile secured line', 'Crime|Documentary', 8.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (152, 'Transformers: Age of Extinction', 'Decentralized intermediate projection', 'Action|Adventure|Sci-Fi', 8.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (153, 'Jim Jefferies: Fully Functional (EPIX)', 'De-engineered 4th generation protocol', 'Comedy', 10.41);
insert into products (product_id, product_name, description, product_category, unit_price) values (154, 'Dead End', 'Visionary bandwidth-monitored internet solution', 'Crime|Drama', 11.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (155, 'Sholay', 'Re-contextualized foreground extranet', 'Action|Adventure|Comedy|Musical|Romance|Thriller', 10.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (156, 'Enough Said', 'Universal tertiary forecast', 'Comedy|Drama|Romance', 8.27);
insert into products (product_id, product_name, description, product_category, unit_price) values (157, 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les)', 'Digitized responsive secured line', 'Drama|Musical|Romance', 8.22);
insert into products (product_id, product_name, description, product_category, unit_price) values (158, 'Tell Them Anything You Want: A Portrait of Maurice Sendak', 'User-friendly empowering architecture', 'Documentary', 9.15);
insert into products (product_id, product_name, description, product_category, unit_price) values (159, 'Sugar & Spice', 'Balanced actuating array', 'Comedy', 11.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (160, 'DOA: Dead or Alive', 'Focused fresh-thinking moderator', 'Action|Adventure', 13.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (161, 'Abbott and Costello Go to Mars', 'Configurable radical orchestration', 'Comedy|Sci-Fi', 12.91);
insert into products (product_id, product_name, description, product_category, unit_price) values (162, 'Grey Gardens', 'Horizontal composite approach', 'Documentary', 8.16);
insert into products (product_id, product_name, description, product_category, unit_price) values (163, 'Pill, The', 'Universal motivating challenge', 'Comedy|Drama|Romance', 14.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (164, 'Zero Hour!', 'Universal intangible functionalities', 'Drama|Thriller', 11.4);
insert into products (product_id, product_name, description, product_category, unit_price) values (165, 'The Big Shave', 'Focused explicit data-warehouse', 'Drama|Horror', 10.55);
insert into products (product_id, product_name, description, product_category, unit_price) values (166, 'Closer to the Moon', 'Sharable dedicated service-desk', 'Comedy|Drama', 12.87);
insert into products (product_id, product_name, description, product_category, unit_price) values (167, 'Coach Carter', 'Optimized tertiary process improvement', 'Drama', 10.62);
insert into products (product_id, product_name, description, product_category, unit_price) values (168, 'Secret Garden, The', 'De-engineered modular adapter', 'Children|Drama', 12.49);
insert into products (product_id, product_name, description, product_category, unit_price) values (169, 'Dyatlov Pass Incident, The (Devil''s Pass)', 'Polarised dynamic methodology', 'Mystery|Thriller', 10.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (170, 'Dogfight', 'Expanded motivating customer loyalty', 'Drama|Romance', 11.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (171, 'Girl, The (Flickan)', 'Front-line object-oriented frame', 'Drama', 10.77);
insert into products (product_id, product_name, description, product_category, unit_price) values (172, 'Bloodsuckers', 'Inverse didactic secured line', 'Action|Horror|Sci-Fi', 14.42);
insert into products (product_id, product_name, description, product_category, unit_price) values (173, 'Lovers and Other Strangers', 'Decentralized encompassing internet solution', 'Comedy', 11.39);
insert into products (product_id, product_name, description, product_category, unit_price) values (174, 'Giant Gila Monster, The', 'Multi-tiered discrete architecture', 'Horror|Sci-Fi', 10.52);
insert into products (product_id, product_name, description, product_category, unit_price) values (175, 'King Boxer: Five Fingers of Death (Tian xia di yi quan)', 'Multi-lateral 24 hour structure', 'Action|Drama|Romance', 6.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (176, 'Blue Ruin', 'Profit-focused even-keeled solution', 'Thriller', 8.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (177, 'Wirey Spindell', 'Networked multi-tasking software', 'Comedy', 7.97);
insert into products (product_id, product_name, description, product_category, unit_price) values (178, 'Redirected', 'Customer-focused actuating system engine', 'Action|Comedy|Crime', 11.03);
insert into products (product_id, product_name, description, product_category, unit_price) values (179, 'Battle of the Bulge', 'Enhanced next generation framework', 'Action|Drama|War', 9.11);
insert into products (product_id, product_name, description, product_category, unit_price) values (180, 'Ankur (The Seedling)', 'Open-architected contextually-based local area network', 'Drama', 5.14);
insert into products (product_id, product_name, description, product_category, unit_price) values (181, 'Man Next Door, The (El hombre de al lado)', 'Networked human-resource local area network', 'Drama', 5.28);
insert into products (product_id, product_name, description, product_category, unit_price) values (182, 'Muppet Christmas: Letters to Santa, A', 'Open-architected asymmetric contingency', 'Children|Comedy', 8.48);
insert into products (product_id, product_name, description, product_category, unit_price) values (183, 'Triggermen', 'Optional stable attitude', 'Comedy|Crime', 10.52);
insert into products (product_id, product_name, description, product_category, unit_price) values (184, 'Played', 'Front-line explicit productivity', 'Crime|Thriller', 13.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (185, 'Nightmare Castle (Amanti d''oltretomba) (Lovers from Beyond the Tomb) (Faceless Monster, The)', 'Streamlined real-time orchestration', 'Horror', 5.22);
insert into products (product_id, product_name, description, product_category, unit_price) values (186, 'Hell and Back Again', 'Expanded executive challenge', 'Documentary|Drama|War', 7.06);
insert into products (product_id, product_name, description, product_category, unit_price) values (187, 'Space Amoeba (Yog: Monster from Space)', 'Virtual regional benchmark', 'Action|Sci-Fi', 7.64);
insert into products (product_id, product_name, description, product_category, unit_price) values (188, 'S.W.A.T.: Firefight', 'Team-oriented bottom-line challenge', 'Action|Crime|Thriller', 5.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (189, 'Crawling Hand, The', 'Multi-tiered 4th generation intranet', 'Horror|Sci-Fi', 14.05);
insert into products (product_id, product_name, description, product_category, unit_price) values (190, 'Milky Way, The (Voie lactée, La)', 'Triple-buffered stable knowledge base', 'Comedy|Drama', 9.64);
insert into products (product_id, product_name, description, product_category, unit_price) values (191, 'Viva Cuba', 'Devolved grid-enabled neural-net', 'Comedy|Drama', 7.61);
insert into products (product_id, product_name, description, product_category, unit_price) values (192, 'Gacy', 'User-centric heuristic array', 'Crime|Drama|Horror|Thriller', 12.45);
insert into products (product_id, product_name, description, product_category, unit_price) values (193, 'Kevin Hart: Seriously Funny', 'Fully-configurable motivating policy', 'Comedy', 10.91);
insert into products (product_id, product_name, description, product_category, unit_price) values (194, 'Hexed', 'Switchable client-server matrices', 'Comedy', 9.36);
insert into products (product_id, product_name, description, product_category, unit_price) values (195, 'Winged Creatures (Fragments)', 'Profit-focused background model', 'Crime|Drama', 14.14);
insert into products (product_id, product_name, description, product_category, unit_price) values (196, 'Dames du Bois de Boulogne, Les (Ladies of the Bois de Boulogne, The) (Ladies of the Park)', 'Synchronised secondary standardization', 'Drama|Romance', 12.53);
insert into products (product_id, product_name, description, product_category, unit_price) values (197, 'The Violent Professionals', 'Centralized human-resource extranet', 'Crime|Drama', 12.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (198, 'American Madness', 'Distributed client-server collaboration', 'Drama', 6.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (199, 'Ernest Goes to Africa', 'Operative composite infrastructure', 'Comedy', 12.46);
insert into products (product_id, product_name, description, product_category, unit_price) values (200, 'Cream Lemon (Kurîmu remon)', 'Multi-channelled real-time knowledge user', 'Comedy|Drama', 7.54);
