insert into product (product_id, product_name, description, product_category, unit_price) values (1, 'Turning Tide (En solitaire)', 'Team-oriented scalable info-mediaries', 'Adventure|Drama', 6.29);
insert into product (product_id, product_name, description, product_category, unit_price) values (2, 'Straight Talk', 'Ameliorated homogeneous framework', 'Comedy', 80.06);
insert into product (product_id, product_name, description, product_category, unit_price) values (3, 'California Solo', 'Function-based 6th generation open architecture', 'Drama', 75.98);
insert into product (product_id, product_name, description, product_category, unit_price) values (4, 'Legacy of Rage', 'Optional client-server service-desk', 'Action', 7.58);
insert into product (product_id, product_name, description, product_category, unit_price) values (5, 'St. Ives', 'Stand-alone hybrid projection', 'Crime|Mystery|Thriller', 52.91);
insert into product (product_id, product_name, description, product_category, unit_price) values (6, 'Trauma', 'Upgradable reciprocal info-mediaries', 'Drama|Mystery|Thriller', 90.32);
insert into product (product_id, product_name, description, product_category, unit_price) values (7, 'Hit Man', 'Exclusive zero administration open architecture', 'Crime|Drama', 75.88);
insert into product (product_id, product_name, description, product_category, unit_price) values (8, 'Dance Me Outside', 'Horizontal radical superstructure', 'Comedy|Drama', 55.57);
insert into product (product_id, product_name, description, product_category, unit_price) values (9, 'Tavarataivas', 'Fully-configurable responsive benchmark', 'Documentary', 42.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (10, '976-EVIL', 'Enhanced regional hierarchy', 'Horror', 75.46);
insert into product (product_id, product_name, description, product_category, unit_price) values (11, 'Monty Python''s Life of Brian', 'Ergonomic asymmetric secured line', 'Comedy', 47.32);
insert into product (product_id, product_name, description, product_category, unit_price) values (12, 'Sister Street Fighter (Onna hissatsu ken)', 'Networked background hardware', 'Action|Drama', 11.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (13, 'Sweeney Todd: The Demon Barber of Fleet Street', 'De-engineered directional orchestration', 'Drama|Horror|Musical|Thriller', 95.41);
insert into product (product_id, product_name, description, product_category, unit_price) values (14, 'Blues Brothers 2000', 'Versatile coherent neural-net', 'Action|Comedy|Musical', 85.26);
insert into product (product_id, product_name, description, product_category, unit_price) values (15, 'Girl', 'Multi-channelled maximized task-force', 'Drama', 99.81);
insert into product (product_id, product_name, description, product_category, unit_price) values (16, 'Night to Remember, A', 'Upgradable context-sensitive website', 'Action|Drama', 68.92);
insert into product (product_id, product_name, description, product_category, unit_price) values (17, 'Bastards of the Party', 'Realigned logistical time-frame', 'Documentary', 55.5);
insert into product (product_id, product_name, description, product_category, unit_price) values (18, 'Someone I Loved (Je l''aimais)', 'Optimized client-server emulation', 'Drama|Romance', 5.9);
insert into product (product_id, product_name, description, product_category, unit_price) values (19, 'Sister Act', 'Automated discrete access', 'Comedy|Crime', 66.06);
insert into product (product_id, product_name, description, product_category, unit_price) values (20, 'Babysitter Wanted', 'Re-engineered zero administration pricing structure', 'Horror|Thriller', 57.62);
insert into product (product_id, product_name, description, product_category, unit_price) values (21, 'Chocolate Strawberry Vanilla', 'Digitized responsive website', 'Comedy|Drama', 82.44);
insert into product (product_id, product_name, description, product_category, unit_price) values (22, 'Charly', 'Expanded 24/7 synergy', 'Drama|Sci-Fi', 10.39);
insert into product (product_id, product_name, description, product_category, unit_price) values (23, 'Pepe', 'Devolved exuding projection', 'Comedy|Musical', 38.49);
insert into product (product_id, product_name, description, product_category, unit_price) values (24, 'Far Out Isn''t Far Enough: The Tomi Ungerer Story', 'Streamlined 24/7 archive', 'Documentary', 13.89);
insert into product (product_id, product_name, description, product_category, unit_price) values (25, 'The Pirates', 'Mandatory upward-trending toolset', 'Adventure', 77.58);
insert into product (product_id, product_name, description, product_category, unit_price) values (26, 'Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite)', 'Ameliorated object-oriented extranet', 'Action', 74.5);
insert into product (product_id, product_name, description, product_category, unit_price) values (27, 'Way Down East', 'Monitored didactic standardization', 'Drama|Romance', 40.75);
insert into product (product_id, product_name, description, product_category, unit_price) values (28, 'Generation X', 'Profound 6th generation intranet', 'Action|Adventure|Sci-Fi', 72.51);
insert into product (product_id, product_name, description, product_category, unit_price) values (29, 'In the Loop', 'Networked next generation budgetary management', 'Comedy', 81.06);
insert into product (product_id, product_name, description, product_category, unit_price) values (30, 'Cinderella Liberty', 'Virtual background policy', 'Drama|Romance', 31.99);
insert into product (product_id, product_name, description, product_category, unit_price) values (31, 'Freeway', 'Synergistic disintermediate complexity', 'Comedy|Crime|Drama|Thriller', 71.32);
insert into product (product_id, product_name, description, product_category, unit_price) values (32, 'Chainsaw Maid', 'Compatible didactic portal', 'Animation', 95.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (33, 'Hells Angels on Wheels', 'Grass-roots 4th generation migration', 'Drama', 23.09);
insert into product (product_id, product_name, description, product_category, unit_price) values (34, 'Badmaash Company', 'Networked upward-trending solution', 'Comedy|Crime|Drama', 83.37);
insert into product (product_id, product_name, description, product_category, unit_price) values (35, 'Possession of Joel Delaney, The', 'Fully-configurable empowering archive', 'Drama|Horror|Thriller', 27.79);
insert into product (product_id, product_name, description, product_category, unit_price) values (36, 'Live Music', 'Organic modular strategy', 'Animation', 40.73);
insert into product (product_id, product_name, description, product_category, unit_price) values (37, 'Assassin Next Door, The (Kirot)', 'Re-engineered foreground productivity', 'Action|Film-Noir|Thriller', 38.24);
insert into product (product_id, product_name, description, product_category, unit_price) values (38, 'Shop Around the Corner, The', 'Realigned tertiary frame', 'Comedy|Drama|Romance', 6.82);
insert into product (product_id, product_name, description, product_category, unit_price) values (39, 'Last Klezmer: Leopold Kozlowski, His Life and Music, The', 'Inverse discrete pricing structure', 'Documentary', 70.7);
insert into product (product_id, product_name, description, product_category, unit_price) values (40, 'Women in Love', 'Distributed foreground toolset', 'Drama|Romance', 37.2);
insert into product (product_id, product_name, description, product_category, unit_price) values (41, 'Curious Case of Benjamin Button, The', 'Inverse contextually-based framework', 'Drama|Fantasy|Mystery|Romance', 81.54);
insert into product (product_id, product_name, description, product_category, unit_price) values (42, 'Horrible Way to Die, A ', 'Reduced contextually-based focus group', 'Horror|Thriller', 81.58);
insert into product (product_id, product_name, description, product_category, unit_price) values (43, 'The Fat Albert Halloween Special', 'Visionary well-modulated function', 'Animation', 41.22);
insert into product (product_id, product_name, description, product_category, unit_price) values (44, 'Lost in Beijing (Ping guo)', 'Re-contextualized scalable emulation', 'Drama', 89.59);
insert into product (product_id, product_name, description, product_category, unit_price) values (45, 'Sunday in the Country, A (Un dimanche à la campagne)', 'Monitored intangible functionalities', 'Drama', 91.18);
insert into product (product_id, product_name, description, product_category, unit_price) values (46, 'Deal, The', 'Universal mobile artificial intelligence', 'Drama', 11.83);
insert into product (product_id, product_name, description, product_category, unit_price) values (47, 'Liberty Stands Still', 'Progressive asymmetric definition', 'Action|Drama|Thriller', 76.33);
insert into product (product_id, product_name, description, product_category, unit_price) values (48, 'Twelve Tasks of Asterix, The (Les douze travaux d''Astérix)', 'Robust clear-thinking hub', 'Action|Adventure|Animation|Children|Comedy|Fantasy', 52.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (49, 'Nina''s Heavenly Delights', 'Persistent local local area network', 'Comedy', 49.96);
insert into product (product_id, product_name, description, product_category, unit_price) values (50, 'Pardon Us', 'Phased interactive architecture', 'Comedy|Crime|Drama|Musical', 59.82);
insert into product (product_id, product_name, description, product_category, unit_price) values (51, 'Domestic Disturbance', 'Cross-group eco-centric superstructure', 'Thriller', 7.66);
insert into product (product_id, product_name, description, product_category, unit_price) values (52, 'The Magical Legend of the Leprechauns', 'Progressive uniform core', 'Adventure|Children|Comedy|Fantasy|Romance', 18.01);
insert into product (product_id, product_name, description, product_category, unit_price) values (53, 'Fourth World War, The', 'Profit-focused optimizing paradigm', 'Documentary', 29.1);
insert into product (product_id, product_name, description, product_category, unit_price) values (54, 'Virgin Suicides, The', 'Seamless interactive groupware', 'Drama|Romance', 25.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (55, 'Edge of the World, The', 'Networked explicit complexity', 'Drama|Romance', 52.74);
insert into product (product_id, product_name, description, product_category, unit_price) values (56, 'Curse of the Hedgehog, The (Blestemul ariciului)', 'Re-contextualized methodical protocol', 'Documentary', 73.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (57, 'The Empty Hours', 'Configurable cohesive groupware', 'Drama|Romance', 44.45);
insert into product (product_id, product_name, description, product_category, unit_price) values (58, 'Saragossa Manuscript, The (Rekopis znaleziony w Saragossie)', 'Adaptive multi-tasking task-force', 'Adventure|Drama|Mystery', 42.18);
insert into product (product_id, product_name, description, product_category, unit_price) values (59, 'Graveyard Shift (Stephen King''s Graveyard Shift)', 'Right-sized incremental neural-net', 'Horror|Thriller', 80.11);
insert into product (product_id, product_name, description, product_category, unit_price) values (60, 'Black Room, The', 'Persistent non-volatile hub', 'Crime|Horror|Thriller', 75.43);
insert into product (product_id, product_name, description, product_category, unit_price) values (61, 'Hitman (Contract Killer) (Sat sau ji wong)', 'Cross-platform value-added instruction set', 'Action|Comedy', 68.18);
insert into product (product_id, product_name, description, product_category, unit_price) values (62, 'Dance Flick', 'Multi-tiered non-volatile Graphical User Interface', 'Comedy|Musical', 94.96);
insert into product (product_id, product_name, description, product_category, unit_price) values (63, 'Love Is News', 'Face to face 6th generation migration', 'Comedy|Romance', 9.39);
insert into product (product_id, product_name, description, product_category, unit_price) values (64, 'Ruhr', 'Enterprise-wide didactic array', 'Documentary', 80.11);
insert into product (product_id, product_name, description, product_category, unit_price) values (65, 'Agnosia', 'Right-sized hybrid open system', 'Drama|Thriller', 77.7);
insert into product (product_id, product_name, description, product_category, unit_price) values (66, 'Calendar', 'Fully-configurable client-server intranet', 'Drama', 16.22);
insert into product (product_id, product_name, description, product_category, unit_price) values (67, 'Wartorn: 1861-2010', 'Fully-configurable client-server forecast', 'Documentary|War', 17.86);
insert into product (product_id, product_name, description, product_category, unit_price) values (68, 'Nine Lives of Tomas Katz, The', 'Inverse heuristic firmware', 'Comedy|Drama|Fantasy', 37.02);
insert into product (product_id, product_name, description, product_category, unit_price) values (69, 'Assassination (Ansatsu) (Assassination, The) (Assassin, The)', 'Cross-platform uniform algorithm', 'Action|Drama', 43.62);
insert into product (product_id, product_name, description, product_category, unit_price) values (70, 'Mysterious Origins of Man', 'Mandatory bandwidth-monitored focus group', 'Documentary', 7.5);
insert into product (product_id, product_name, description, product_category, unit_price) values (71, 'Knight''s Tale, A', 'Optional eco-centric knowledge base', 'Action|Comedy|Romance', 44.39);
insert into product (product_id, product_name, description, product_category, unit_price) values (72, 'Moonstruck', 'Progressive exuding conglomeration', 'Comedy|Romance', 56.27);
insert into product (product_id, product_name, description, product_category, unit_price) values (73, 'Somersault', 'Grass-roots actuating success', 'Drama', 15.89);
insert into product (product_id, product_name, description, product_category, unit_price) values (74, 'Hunter Prey', 'Expanded bifurcated neural-net', 'Sci-Fi', 56.71);
insert into product (product_id, product_name, description, product_category, unit_price) values (75, 'Dolores Claiborne', 'Expanded tangible function', 'Drama|Thriller', 75.25);
insert into product (product_id, product_name, description, product_category, unit_price) values (76, 'Heaven Help Us', 'Extended impactful approach', 'Comedy|Drama', 78.27);
insert into product (product_id, product_name, description, product_category, unit_price) values (77, 'Peculiarities of the National Hunt (Osobennosti natsionalnoy okhoty) ', 'Networked dynamic time-frame', 'Comedy', 66.86);
insert into product (product_id, product_name, description, product_category, unit_price) values (78, 'Story Written with Water, A (Mizu de kakareta monogatari)', 'Multi-tiered upward-trending migration', 'Drama', 95.36);
insert into product (product_id, product_name, description, product_category, unit_price) values (79, 'Elysium', 'Decentralized 3rd generation alliance', 'Action|Drama|Sci-Fi|IMAX', 18.66);
insert into product (product_id, product_name, description, product_category, unit_price) values (80, 'Maniac', 'Visionary interactive project', 'Horror|Thriller', 52.19);
insert into product (product_id, product_name, description, product_category, unit_price) values (81, 'Sun Also Rises, The (Tai yang zhao chang sheng qi)', 'Total fresh-thinking utilisation', 'Drama', 75.97);
insert into product (product_id, product_name, description, product_category, unit_price) values (82, 'Love Is All There Is', 'Polarised homogeneous Graphic Interface', 'Comedy|Drama', 73.19);
insert into product (product_id, product_name, description, product_category, unit_price) values (83, 'Rage in Heaven', 'Enhanced intangible protocol', 'Drama|Thriller', 46.71);
insert into product (product_id, product_name, description, product_category, unit_price) values (84, 'Pure', 'Cross-platform intangible function', 'Drama', 10.68);
insert into product (product_id, product_name, description, product_category, unit_price) values (85, 'Tale of Two Cities, A', 'Self-enabling cohesive capability', 'Drama', 85.44);
insert into product (product_id, product_name, description, product_category, unit_price) values (86, 'Excuse My Dust', 'Integrated intangible installation', 'Comedy|Musical', 27.9);
insert into product (product_id, product_name, description, product_category, unit_price) values (87, 'Changing Times (Les temps qui changent)', 'Organic upward-trending concept', 'Drama|Romance', 99.7);
insert into product (product_id, product_name, description, product_category, unit_price) values (88, 'Rains Came, The', 'Cloned clear-thinking database', 'Adventure|Drama|Romance', 49.85);
insert into product (product_id, product_name, description, product_category, unit_price) values (89, 'Kisses (Kuchizuke)', 'Balanced bandwidth-monitored local area network', 'Drama|Romance', 85.61);
insert into product (product_id, product_name, description, product_category, unit_price) values (90, 'Sherlock Holmes and the Voice of Terror', 'Upgradable dynamic attitude', 'Crime|Mystery|War', 75.66);
insert into product (product_id, product_name, description, product_category, unit_price) values (91, 'Bling: A Planet Rock', 'Grass-roots methodical function', 'Documentary', 37.77);
insert into product (product_id, product_name, description, product_category, unit_price) values (92, 'The Strength of Water', 'Mandatory secondary hierarchy', '(no genres listed)', 99.66);
insert into product (product_id, product_name, description, product_category, unit_price) values (93, 'Discreet Charm of the Bourgeoisie, The (Charme discret de la bourgeoisie, Le)', 'Robust multimedia knowledge user', 'Comedy|Drama|Fantasy', 72.92);
insert into product (product_id, product_name, description, product_category, unit_price) values (94, 'Palermo Shooting', 'Streamlined coherent help-desk', 'Drama', 96.17);
insert into product (product_id, product_name, description, product_category, unit_price) values (95, 'Shooting Gallery', 'Self-enabling even-keeled project', 'Crime|Drama|Thriller', 41.24);
insert into product (product_id, product_name, description, product_category, unit_price) values (96, 'Helen of Troy', 'Optimized motivating circuit', 'Action|Adventure|Drama|Romance', 53.02);
insert into product (product_id, product_name, description, product_category, unit_price) values (97, 'Take Me Home', 'Exclusive responsive hardware', 'Comedy|Romance', 65.84);
insert into product (product_id, product_name, description, product_category, unit_price) values (98, 'Blindness', 'User-friendly heuristic circuit', 'Drama|Thriller', 31.32);
insert into product (product_id, product_name, description, product_category, unit_price) values (99, 'Captain Abu Raed', 'Compatible homogeneous success', 'Drama', 46.18);
insert into product (product_id, product_name, description, product_category, unit_price) values (100, 'Bad Company', 'Down-sized exuding time-frame', 'Action|Crime|Drama', 35.66);
insert into product (product_id, product_name, description, product_category, unit_price) values (101, 'Last Ferry, The (Ostatni prom)', 'Reactive mission-critical intranet', 'Drama', 51.08);
insert into product (product_id, product_name, description, product_category, unit_price) values (102, 'Wolves', 'Managed modular website', 'Documentary|IMAX', 43.21);
insert into product (product_id, product_name, description, product_category, unit_price) values (103, 'Ghost in the Shell (Kôkaku kidôtai)', 'Compatible encompassing standardization', 'Animation|Sci-Fi', 71.1);
insert into product (product_id, product_name, description, product_category, unit_price) values (104, 'Ernest Scared Stupid', 'Cross-group clear-thinking superstructure', 'Comedy', 92.15);
insert into product (product_id, product_name, description, product_category, unit_price) values (105, 'Cold Prey III (Fritt Vilt III)', 'Customizable upward-trending matrices', 'Horror', 80.96);
insert into product (product_id, product_name, description, product_category, unit_price) values (106, 'The Brain', 'Triple-buffered non-volatile definition', 'Comedy|Crime', 87.49);
insert into product (product_id, product_name, description, product_category, unit_price) values (107, 'Mr. Jones', 'Virtual client-driven encoding', 'Drama|Romance', 32.57);
insert into product (product_id, product_name, description, product_category, unit_price) values (108, 'Flow', 'Expanded analyzing matrix', 'Drama', 20.92);
insert into product (product_id, product_name, description, product_category, unit_price) values (109, 'Funny Thing Happened on the Way to the Forum, A', 'Front-line stable emulation', 'Comedy|Musical', 50.69);
insert into product (product_id, product_name, description, product_category, unit_price) values (110, 'I Met Him in Paris', 'Horizontal zero defect circuit', 'Comedy|Romance', 95.59);
insert into product (product_id, product_name, description, product_category, unit_price) values (111, 'Kitchen in Paris', 'Optimized holistic projection', 'Comedy', 56.69);
insert into product (product_id, product_name, description, product_category, unit_price) values (112, 'Mighty Joe Young', 'Front-line zero administration customer loyalty', 'Action|Adventure|Drama|Fantasy|Thriller', 37.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (113, 'Some Girls', 'Balanced composite orchestration', 'Comedy|Drama|Romance', 98.14);
insert into product (product_id, product_name, description, product_category, unit_price) values (114, 'Juwanna Mann', 'Up-sized grid-enabled service-desk', 'Comedy', 29.35);
insert into product (product_id, product_name, description, product_category, unit_price) values (115, 'Muppets Most Wanted', 'Face to face intangible structure', 'Adventure|Comedy|Crime', 9.68);
insert into product (product_id, product_name, description, product_category, unit_price) values (116, 'Sunset Strip', 'Managed local infrastructure', 'Comedy', 31.06);
insert into product (product_id, product_name, description, product_category, unit_price) values (117, 'China Syndrome, The', 'Fully-configurable heuristic service-desk', 'Drama|Thriller', 67.42);
insert into product (product_id, product_name, description, product_category, unit_price) values (118, 'My Cousin Vinny', 'Sharable coherent productivity', 'Comedy', 45.69);
insert into product (product_id, product_name, description, product_category, unit_price) values (119, 'Hope Springs', 'Synergized holistic solution', 'Comedy|Romance', 29.08);
insert into product (product_id, product_name, description, product_category, unit_price) values (120, 'Glitterbug', 'Function-based high-level adapter', '(no genres listed)', 72.21);
insert into product (product_id, product_name, description, product_category, unit_price) values (121, 'Groove Tube, The', 'Expanded executive migration', 'Comedy', 45.01);
insert into product (product_id, product_name, description, product_category, unit_price) values (122, 'Maximum Overdrive', 'Customer-focused cohesive knowledge base', 'Horror', 65.39);
insert into product (product_id, product_name, description, product_category, unit_price) values (123, 'Carlito''s Way', 'Organized maximized system engine', 'Crime|Drama', 36.5);
insert into product (product_id, product_name, description, product_category, unit_price) values (124, 'Journey to the Center of the Earth', 'Managed didactic workforce', 'Action|Adventure|Sci-Fi', 50.82);
insert into product (product_id, product_name, description, product_category, unit_price) values (125, 'My Mother (Ma mère)', 'Open-source optimal flexibility', 'Drama', 20.2);
insert into product (product_id, product_name, description, product_category, unit_price) values (126, 'Girl from Jones Beach, The', 'Right-sized eco-centric task-force', 'Comedy', 92.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (127, 'Franklyn', 'Total intermediate migration', 'Drama|Fantasy|Romance|Thriller', 17.23);
insert into product (product_id, product_name, description, product_category, unit_price) values (128, 'Passeio com Johnny Guitar', 'Cross-platform 5th generation model', '(no genres listed)', 98.32);
insert into product (product_id, product_name, description, product_category, unit_price) values (129, 'Gothika', 'Switchable asymmetric circuit', 'Horror|Thriller', 84.03);
insert into product (product_id, product_name, description, product_category, unit_price) values (130, 'Ruins', 'Seamless actuating initiative', 'Documentary', 41.97);
insert into product (product_id, product_name, description, product_category, unit_price) values (131, 'Under Suspicion', 'Centralized scalable approach', 'Crime|Drama|Thriller', 76.48);
insert into product (product_id, product_name, description, product_category, unit_price) values (132, 'Bourne Legacy, The', 'Configurable exuding strategy', 'Action|Adventure|Drama|Thriller|IMAX', 65.73);
insert into product (product_id, product_name, description, product_category, unit_price) values (133, 'Truman Show, The', 'Organic context-sensitive focus group', 'Comedy|Drama|Sci-Fi', 16.23);
insert into product (product_id, product_name, description, product_category, unit_price) values (134, 'Walkabout', 'Innovative demand-driven support', 'Adventure|Drama', 8.75);
insert into product (product_id, product_name, description, product_category, unit_price) values (135, 'Boston Strangler, The', 'Optimized bottom-line alliance', 'Crime|Drama|Mystery|Thriller', 23.0);
insert into product (product_id, product_name, description, product_category, unit_price) values (136, 'Breakin'' All the Rules', 'Visionary multi-tasking core', 'Comedy|Romance', 81.04);
insert into product (product_id, product_name, description, product_category, unit_price) values (137, 'London to Brighton', 'Versatile systematic parallelism', 'Crime|Drama|Thriller', 37.87);
insert into product (product_id, product_name, description, product_category, unit_price) values (138, 'Pandorum', 'Proactive national adapter', 'Horror|Sci-Fi|Thriller', 84.89);
insert into product (product_id, product_name, description, product_category, unit_price) values (139, 'Once Upon a Scoundrel', 'Exclusive composite knowledge base', 'Comedy', 25.61);
insert into product (product_id, product_name, description, product_category, unit_price) values (140, 'Front, The', 'Switchable neutral portal', 'Comedy|Drama', 46.29);
insert into product (product_id, product_name, description, product_category, unit_price) values (141, 'Banshee Chapter, The', 'Streamlined web-enabled paradigm', 'Horror|Thriller', 52.73);
insert into product (product_id, product_name, description, product_category, unit_price) values (142, 'Marshal of Finland, The (Suomen Marsalkka)', 'Multi-tiered logistical middleware', 'Drama|Romance', 30.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (143, 'Zombie Island Massacre', 'Automated zero administration task-force', 'Horror', 17.03);
insert into product (product_id, product_name, description, product_category, unit_price) values (144, 'Coffin Rock', 'Seamless zero defect info-mediaries', 'Thriller', 92.07);
insert into product (product_id, product_name, description, product_category, unit_price) values (145, 'Poison Ivy', 'Profound explicit project', 'Drama|Thriller', 61.55);
insert into product (product_id, product_name, description, product_category, unit_price) values (146, 'Pulp Fiction', 'Mandatory value-added encoding', 'Comedy|Crime|Drama|Thriller', 31.47);
insert into product (product_id, product_name, description, product_category, unit_price) values (147, 'Proof', 'Enhanced systemic approach', 'Comedy|Drama|Romance', 87.7);
insert into product (product_id, product_name, description, product_category, unit_price) values (148, 'Runaways, The', 'Future-proofed cohesive matrices', 'Drama|Musical', 59.82);
insert into product (product_id, product_name, description, product_category, unit_price) values (149, 'Gold', 'Expanded incremental Graphic Interface', 'Action|Adventure|Drama|Thriller', 79.31);
insert into product (product_id, product_name, description, product_category, unit_price) values (150, 'Grocer''s Son, The (Fils de l''épicier, Le)', 'Total homogeneous monitoring', 'Drama|Romance', 92.47);
insert into product (product_id, product_name, description, product_category, unit_price) values (151, 'The Chumscrubber', 'Reverse-engineered needs-based protocol', 'Comedy|Drama', 55.46);
insert into product (product_id, product_name, description, product_category, unit_price) values (152, 'Woman of Affairs, A', 'Polarised fresh-thinking product', 'Drama', 50.68);
insert into product (product_id, product_name, description, product_category, unit_price) values (153, 'Down to Earth', 'Digitized didactic process improvement', 'Comedy|Fantasy|Romance', 18.06);
insert into product (product_id, product_name, description, product_category, unit_price) values (154, 'Animals are Beautiful People', 'Reduced context-sensitive adapter', 'Comedy|Documentary', 51.22);
insert into product (product_id, product_name, description, product_category, unit_price) values (155, 'Vera Drake', 'Open-source fresh-thinking flexibility', 'Drama', 13.65);
insert into product (product_id, product_name, description, product_category, unit_price) values (156, 'Cabinet of Dr. Caligari, The (Cabinet des Dr. Caligari., Das)', 'Polarised actuating strategy', 'Crime|Fantasy|Horror', 92.44);
insert into product (product_id, product_name, description, product_category, unit_price) values (157, 'King of California', 'Right-sized composite capacity', 'Comedy', 74.57);
insert into product (product_id, product_name, description, product_category, unit_price) values (158, 'Winnie the Pooh and a Day for Eeyore', 'Quality-focused discrete data-warehouse', 'Animation|Children', 23.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (159, 'Newsies', 'Multi-tiered bi-directional protocol', 'Children|Musical', 68.05);
insert into product (product_id, product_name, description, product_category, unit_price) values (160, 'Prinsessa (Starring Maja)', 'Streamlined bottom-line toolset', 'Drama', 70.71);
insert into product (product_id, product_name, description, product_category, unit_price) values (161, 'Fellini''s Roma (Roma)', 'Polarised maximized framework', 'Drama', 76.98);
insert into product (product_id, product_name, description, product_category, unit_price) values (162, 'Moon Over Parador', 'User-friendly logistical contingency', 'Comedy', 32.46);
insert into product (product_id, product_name, description, product_category, unit_price) values (163, 'Liquid Sky', 'Total upward-trending protocol', 'Comedy|Sci-Fi', 85.22);
insert into product (product_id, product_name, description, product_category, unit_price) values (164, 'Cliffhanger', 'De-engineered 3rd generation moratorium', 'Action|Adventure|Thriller', 23.66);
insert into product (product_id, product_name, description, product_category, unit_price) values (165, '1941', 'Up-sized stable website', 'Comedy|War', 36.2);
insert into product (product_id, product_name, description, product_category, unit_price) values (166, 'Phantasm II', 'Cross-group 24/7 toolset', 'Action|Fantasy|Horror|Sci-Fi|Thriller', 95.52);
insert into product (product_id, product_name, description, product_category, unit_price) values (167, 'Other Voices, Other Rooms', 'Organized demand-driven hierarchy', 'Drama', 28.93);
insert into product (product_id, product_name, description, product_category, unit_price) values (168, 'Head Over Heels (De Pernas pro Ar)', 'Implemented 3rd generation website', 'Comedy', 42.14);
insert into product (product_id, product_name, description, product_category, unit_price) values (169, 'Girl 6', 'Innovative attitude-oriented implementation', 'Comedy|Drama', 70.07);
insert into product (product_id, product_name, description, product_category, unit_price) values (170, 'Blind Side, The', 'Balanced responsive Graphical User Interface', 'Drama', 95.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (171, 'Beethoven''s Treasure Tail', 'Versatile bottom-line task-force', 'Action|Adventure|Children', 60.27);
insert into product (product_id, product_name, description, product_category, unit_price) values (172, 'Southerner, The', 'Function-based bottom-line productivity', 'Drama', 68.32);
insert into product (product_id, product_name, description, product_category, unit_price) values (173, 'Happy', 'Public-key uniform open architecture', 'Documentary|Drama', 54.61);
insert into product (product_id, product_name, description, product_category, unit_price) values (174, 'Funny About Love', 'Customizable responsive methodology', 'Comedy|Romance', 54.24);
insert into product (product_id, product_name, description, product_category, unit_price) values (175, 'Funeral Parade of Roses (Bara no sôretsu)', 'Vision-oriented object-oriented monitoring', 'Drama', 17.16);
insert into product (product_id, product_name, description, product_category, unit_price) values (176, 'Down in the Delta', 'Seamless fresh-thinking emulation', 'Drama', 26.3);
insert into product (product_id, product_name, description, product_category, unit_price) values (177, 'Punishment Park', 'Future-proofed intermediate Graphic Interface', 'Drama|Thriller', 35.5);
insert into product (product_id, product_name, description, product_category, unit_price) values (178, 'Man of the World', 'Public-key content-based focus group', 'Drama|Romance', 95.06);
insert into product (product_id, product_name, description, product_category, unit_price) values (179, 'Mille bolle blu', 'Advanced stable utilisation', 'Comedy', 90.94);
insert into product (product_id, product_name, description, product_category, unit_price) values (180, 'Sam''s Song', 'Networked client-server capability', 'Drama', 11.21);
insert into product (product_id, product_name, description, product_category, unit_price) values (181, 'Turbo', 'Enhanced 24/7 collaboration', 'Adventure|Animation|Children|Comedy|Fantasy', 46.09);
insert into product (product_id, product_name, description, product_category, unit_price) values (182, 'Point and Shoot', 'Re-engineered radical firmware', 'Documentary', 89.67);
insert into product (product_id, product_name, description, product_category, unit_price) values (183, 'Dakota', 'Operative leading edge help-desk', 'Western', 55.61);
insert into product (product_id, product_name, description, product_category, unit_price) values (184, 'Penthouse North', 'User-friendly regional extranet', 'Drama|Mystery|Thriller', 74.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (185, 'Maximum Risk', 'Automated maximized strategy', 'Action|Adventure|Thriller', 12.83);
insert into product (product_id, product_name, description, product_category, unit_price) values (186, 'Possession', 'User-friendly stable pricing structure', 'Drama|Romance', 67.21);
insert into product (product_id, product_name, description, product_category, unit_price) values (187, 'Calcium Kid, The', 'Reactive even-keeled architecture', 'Comedy', 81.0);
insert into product (product_id, product_name, description, product_category, unit_price) values (188, 'The Wait', 'Re-contextualized system-worthy definition', 'Drama|Thriller', 59.6);
insert into product (product_id, product_name, description, product_category, unit_price) values (189, 'Patterns', 'Enterprise-wide encompassing time-frame', 'Drama', 71.45);
insert into product (product_id, product_name, description, product_category, unit_price) values (190, 'Strictly Ballroom', 'Automated 5th generation hardware', 'Comedy|Romance', 99.84);
insert into product (product_id, product_name, description, product_category, unit_price) values (191, 'Chatroom', 'Secured mission-critical flexibility', 'Crime|Drama|Mystery|Thriller', 35.57);
insert into product (product_id, product_name, description, product_category, unit_price) values (192, 'Arise, My Love', 'Synergistic maximized capability', 'Comedy|Drama|Romance', 60.22);
insert into product (product_id, product_name, description, product_category, unit_price) values (193, 'Car 54, Where Are You?', 'Decentralized 24 hour initiative', 'Comedy', 99.68);
insert into product (product_id, product_name, description, product_category, unit_price) values (194, 'California Conquest', 'Grass-roots even-keeled productivity', 'Adventure|Romance|Western', 59.79);
insert into product (product_id, product_name, description, product_category, unit_price) values (195, 'Beau Pere (a.k.a. Stepfather) (Beau-père)', 'Proactive transitional intranet', 'Drama', 85.9);
insert into product (product_id, product_name, description, product_category, unit_price) values (196, 'Dirty Dozen: Next Mission, The', 'Configurable high-level installation', 'Action|War', 43.71);
insert into product (product_id, product_name, description, product_category, unit_price) values (197, 'Bride of Re-Animator', 'Expanded secondary encryption', 'Comedy|Horror', 15.56);
insert into product (product_id, product_name, description, product_category, unit_price) values (198, 'Zerophilia', 'Digitized maximized benchmark', 'Comedy|Romance', 87.61);
insert into product (product_id, product_name, description, product_category, unit_price) values (199, 'Picture of Dorian Gray, The', 'Open-source object-oriented infrastructure', 'Drama|Fantasy|Horror', 35.82);
insert into product (product_id, product_name, description, product_category, unit_price) values (200, 'Harry Potter and the Deathly Hallows: Part 1', 'Enterprise-wide user-facing knowledge base', 'Action|Adventure|Fantasy|IMAX', 83.37);
