insert into products (product_id, product_name, description, product_category, unit_price) values (1, 'Witching and Bitching (Brujas de Zugarramurdi, Las)', 'Optimized content-based circuit', 'Comedy|Fantasy', 89.29);
insert into products (product_id, product_name, description, product_category, unit_price) values (2, 'Postman, The (Postino, Il)', 'Focused motivating implementation', 'Comedy|Drama|Romance', 47.2);
insert into products (product_id, product_name, description, product_category, unit_price) values (3, 'It''s a Small World', 'Inverse multi-state alliance', 'Comedy', 90.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (4, 'Crow: City of Angels, The', 'Centralized encompassing capacity', 'Action|Thriller', 16.62);
insert into products (product_id, product_name, description, product_category, unit_price) values (5, 'Wrestling Ernest Hemingway', 'Vision-oriented multi-tasking interface', 'Drama|Romance', 22.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (6, 'Get Hard', 'Triple-buffered multi-tasking access', 'Comedy', 42.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (7, 'Life', 'Profound fresh-thinking synergy', 'Comedy|Crime|Drama', 8.26);
insert into products (product_id, product_name, description, product_category, unit_price) values (8, 'The New Centurions', 'Fundamental empowering moderator', 'Action|Crime|Drama', 86.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (9, 'La Belle Verte', 'Future-proofed real-time benchmark', 'Comedy', 10.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (10, 'Sol ', 'Focused demand-driven circuit', 'Sci-Fi', 74.23);
insert into products (product_id, product_name, description, product_category, unit_price) values (11, 'Anne Frank Remembered', 'Automated static matrices', 'Documentary', 47.94);
insert into products (product_id, product_name, description, product_category, unit_price) values (12, 'Snitch', 'Programmable regional local area network', 'Action|Drama|Thriller', 92.94);
insert into products (product_id, product_name, description, product_category, unit_price) values (13, 'Divorce Iranian Style', 'Enhanced bottom-line product', 'Documentary', 15.86);
insert into products (product_id, product_name, description, product_category, unit_price) values (14, 'Intimacy', 'Synchronised local forecast', 'Drama', 68.2);
insert into products (product_id, product_name, description, product_category, unit_price) values (15, 'Piripäiväkirja', 'Innovative well-modulated forecast', 'Documentary', 43.07);
insert into products (product_id, product_name, description, product_category, unit_price) values (16, 'Smokin'' Aces', 'Open-source 5th generation array', 'Action|Crime|Drama|Thriller', 43.81);
insert into products (product_id, product_name, description, product_category, unit_price) values (17, 'Spirit of the Beehive, The (Espíritu de la colmena, El)', 'Fundamental stable contingency', 'Drama|Horror|Mystery', 12.73);
insert into products (product_id, product_name, description, product_category, unit_price) values (18, 'Armored Car Robbery', 'Fundamental methodical forecast', 'Crime|Film-Noir|Thriller', 31.13);
insert into products (product_id, product_name, description, product_category, unit_price) values (19, '7 Boxes (7 cajas)', 'Expanded discrete product', 'Action|Thriller', 77.98);
insert into products (product_id, product_name, description, product_category, unit_price) values (20, 'Café Metropole', 'Team-oriented multi-tasking moratorium', 'Comedy|Drama|Romance', 84.22);
insert into products (product_id, product_name, description, product_category, unit_price) values (21, 'Giant Mechanical Man, The', 'Switchable empowering analyzer', 'Comedy|Drama|Romance', 20.72);
insert into products (product_id, product_name, description, product_category, unit_price) values (22, 'Mickey''s Twice Upon a Christmas', 'Enterprise-wide client-driven workforce', 'Animation|Children|Comedy', 92.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (23, 'Castle Keep', 'Monitored value-added pricing structure', 'Drama|War', 16.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (24, 'How to Make Money Selling Drugs', 'Cross-group discrete encryption', 'Documentary', 59.39);
insert into products (product_id, product_name, description, product_category, unit_price) values (25, '40 Guns to Apache Pass', 'Extended human-resource project', 'Adventure|Romance|Western', 75.17);
insert into products (product_id, product_name, description, product_category, unit_price) values (26, 'Three Stooges, The', 'Innovative actuating system engine', 'Comedy', 99.86);
insert into products (product_id, product_name, description, product_category, unit_price) values (27, 'Wedding Gift, The', 'Reactive composite superstructure', 'Drama|Romance', 82.7);
insert into products (product_id, product_name, description, product_category, unit_price) values (28, 'Speaking Parts', 'Optimized mobile migration', 'Drama', 46.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (29, 'Nothing to Lose (a.k.a. Ten Benny)', 'Customer-focused explicit groupware', 'Drama', 94.83);
insert into products (product_id, product_name, description, product_category, unit_price) values (30, 'Mystic Pizza', 'Streamlined foreground groupware', 'Comedy|Drama|Romance', 85.75);
insert into products (product_id, product_name, description, product_category, unit_price) values (31, 'Gothika', 'Inverse tangible infrastructure', 'Horror|Thriller', 38.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (32, 'Mad Hot Ballroom', 'Streamlined mission-critical workforce', 'Children|Documentary', 71.7);
insert into products (product_id, product_name, description, product_category, unit_price) values (33, 'Downtown', 'Multi-layered leading edge application', 'Action|Comedy', 51.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (34, 'Underworld: Awakening', 'Progressive multi-tasking superstructure', 'Action|Fantasy|Horror|IMAX', 99.63);
insert into products (product_id, product_name, description, product_category, unit_price) values (35, 'How 2 Build a Rapper', 'Front-line intangible Graphical User Interface', 'Comedy', 64.27);
insert into products (product_id, product_name, description, product_category, unit_price) values (36, 'Sharktopus', 'Right-sized bottom-line solution', 'Action|Horror|Sci-Fi', 29.68);
insert into products (product_id, product_name, description, product_category, unit_price) values (37, 'Prison', 'Programmable fresh-thinking website', 'Crime|Drama|Horror|Thriller', 20.31);
insert into products (product_id, product_name, description, product_category, unit_price) values (38, 'At Berkeley', 'Future-proofed neutral adapter', 'Documentary', 33.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (39, 'Temp, The', 'Profit-focused reciprocal hub', 'Drama|Thriller', 39.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (40, 'In the Time of the Butterflies', 'Phased actuating complexity', 'Crime|Drama', 60.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (41, 'Angel''s Leap', 'Face to face national policy', 'Crime', 87.36);
insert into products (product_id, product_name, description, product_category, unit_price) values (42, 'See Heaven', 'Exclusive local paradigm', 'Documentary', 45.34);
insert into products (product_id, product_name, description, product_category, unit_price) values (43, 'Breathing Room', 'Persistent well-modulated success', 'Horror|Mystery|Thriller', 81.02);
insert into products (product_id, product_name, description, product_category, unit_price) values (44, 'Pearls of the Deep (Perlicky na dne)', 'Right-sized bi-directional website', 'Comedy', 11.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (45, 'Switch', 'Visionary interactive parallelism', 'Comedy|Crime|Fantasy', 83.1);
insert into products (product_id, product_name, description, product_category, unit_price) values (46, 'Where the Sidewalk Ends', 'Sharable multi-tasking conglomeration', 'Crime|Drama|Film-Noir', 47.89);
insert into products (product_id, product_name, description, product_category, unit_price) values (47, 'Magic of Ordinary Days, The', 'Advanced background capability', 'Drama', 13.08);
insert into products (product_id, product_name, description, product_category, unit_price) values (48, 'Villa Rides!', 'De-engineered logistical core', 'War|Western', 79.03);
insert into products (product_id, product_name, description, product_category, unit_price) values (49, 'Hotel Hell Vacation', 'Profound composite frame', 'Comedy', 37.24);
insert into products (product_id, product_name, description, product_category, unit_price) values (50, 'Deserter (Dezertir)', 'Implemented holistic approach', 'Drama', 45.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (51, 'Town Called Hell, A', 'Networked human-resource matrices', 'Action|Comedy|Drama|Western', 66.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (52, 'Suicide Club', 'Self-enabling impactful structure', 'Adventure|Comedy|Drama', 80.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (53, 'Woman Under the Influence, A', 'Customizable object-oriented challenge', 'Drama', 21.18);
insert into products (product_id, product_name, description, product_category, unit_price) values (54, 'My Friend Henry (Ystäväni Henry)', 'Decentralized intangible artificial intelligence', 'Children|Drama', 21.15);
insert into products (product_id, product_name, description, product_category, unit_price) values (55, 'Six-String Samurai', 'Mandatory multimedia pricing structure', 'Action|Adventure|Sci-Fi', 76.53);
insert into products (product_id, product_name, description, product_category, unit_price) values (56, 'Melissa P.', 'Function-based mobile portal', 'Drama', 65.4);
insert into products (product_id, product_name, description, product_category, unit_price) values (57, 'Monkey''s Mask, The', 'Compatible tertiary instruction set', 'Crime|Mystery', 93.74);
insert into products (product_id, product_name, description, product_category, unit_price) values (58, 'Queen of Hearts', 'Reverse-engineered zero tolerance project', 'Comedy|Drama|Romance', 18.72);
insert into products (product_id, product_name, description, product_category, unit_price) values (59, 'Beauty and the Beast (Beauty and the Beasts: A Dark Tale)', 'Phased full-range budgetary management', 'Fantasy', 75.6);
insert into products (product_id, product_name, description, product_category, unit_price) values (60, 'Sylvia and the Ghost', 'Monitored foreground protocol', 'Comedy|Fantasy|Romance', 61.68);
insert into products (product_id, product_name, description, product_category, unit_price) values (61, 'Baader Meinhof Komplex, Der', 'Synchronised secondary workforce', 'Action|Crime|Drama|Thriller', 31.36);
insert into products (product_id, product_name, description, product_category, unit_price) values (62, 'En på miljonen', 'Grass-roots bandwidth-monitored open architecture', '(no genres listed)', 54.96);
insert into products (product_id, product_name, description, product_category, unit_price) values (63, 'Seven (a.k.a. Se7en)', 'Realigned bi-directional focus group', 'Mystery|Thriller', 23.02);
insert into products (product_id, product_name, description, product_category, unit_price) values (64, 'The Forgotten Faces', 'Ergonomic 6th generation software', '(no genres listed)', 77.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (65, 'I Want Someone to Eat Cheese With', 'Secured national conglomeration', 'Comedy', 19.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (66, 'Where''s Marlowe?', 'Digitized motivating time-frame', 'Comedy', 67.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (67, 'John Wick', 'Versatile context-sensitive adapter', 'Action|Thriller', 60.73);
insert into products (product_id, product_name, description, product_category, unit_price) values (68, 'Snowbeast', 'Horizontal mobile parallelism', 'Horror', 67.39);
insert into products (product_id, product_name, description, product_category, unit_price) values (69, 'Crystal Lake Memories: The Complete History of Friday the 13th', 'Mandatory impactful solution', 'Documentary|Horror', 25.59);
insert into products (product_id, product_name, description, product_category, unit_price) values (70, 'In the Hands of the Gods', 'Pre-emptive static strategy', 'Documentary', 27.03);
insert into products (product_id, product_name, description, product_category, unit_price) values (71, 'I Know Where I''m Going!', 'User-centric homogeneous software', 'Drama|Romance|War', 7.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (72, 'River''s Edge', 'Extended optimal interface', 'Crime|Drama', 40.35);
insert into products (product_id, product_name, description, product_category, unit_price) values (73, 'Death Machine', 'Exclusive 3rd generation concept', 'Action|Sci-Fi', 14.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (74, 'Aloft', 'Ameliorated modular complexity', 'Drama', 26.03);
insert into products (product_id, product_name, description, product_category, unit_price) values (75, 'Siberian Education (Educazione siberiana)', 'Cross-platform demand-driven complexity', 'Drama', 89.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (76, 'Cronos', 'Object-based neutral installation', 'Drama|Horror', 32.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (77, 'Going Ape!', 'Assimilated interactive contingency', 'Comedy', 70.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (78, 'If You Are the One', 'Optimized value-added analyzer', 'Comedy|Romance', 44.61);
insert into products (product_id, product_name, description, product_category, unit_price) values (79, 'Little Girl Who Conquered Time, The (Toki o kakeru shôjo)', 'Managed analyzing access', 'Romance|Sci-Fi', 47.25);
insert into products (product_id, product_name, description, product_category, unit_price) values (80, 'Jerichow', 'Managed composite complexity', 'Drama', 18.12);
insert into products (product_id, product_name, description, product_category, unit_price) values (81, 'Aamir', 'Operative maximized customer loyalty', 'Drama|Thriller', 99.35);
insert into products (product_id, product_name, description, product_category, unit_price) values (82, 'My New Gun', 'Up-sized upward-trending algorithm', 'Comedy', 51.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (83, 'Aspen', 'De-engineered systematic pricing structure', 'Documentary', 7.89);
insert into products (product_id, product_name, description, product_category, unit_price) values (84, 'Feast of July', 'Operative reciprocal installation', 'Drama', 48.7);
insert into products (product_id, product_name, description, product_category, unit_price) values (85, 'Recruiter, The', 'Upgradable even-keeled open architecture', 'Documentary', 95.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (86, 'Santa with Muscles', 'Seamless transitional database', 'Comedy', 34.46);
insert into products (product_id, product_name, description, product_category, unit_price) values (87, 'Gervaise', 'Multi-channelled well-modulated flexibility', 'Drama', 73.35);
insert into products (product_id, product_name, description, product_category, unit_price) values (88, 'Man and a Woman, A (Un homme et une femme)', 'Configurable value-added hub', 'Drama|Romance', 55.02);
insert into products (product_id, product_name, description, product_category, unit_price) values (89, 'Herod''s Law (Ley de Herodes, La)', 'Face to face radical capacity', 'Comedy|Crime|Mystery', 11.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (90, 'New Year''s Eve', 'Reverse-engineered intangible groupware', 'Comedy|Romance', 78.25);
insert into products (product_id, product_name, description, product_category, unit_price) values (91, 'Rough Magic', 'Fully-configurable secondary flexibility', 'Drama|Romance', 41.06);
insert into products (product_id, product_name, description, product_category, unit_price) values (92, 'Storm Warning', 'Organic systematic policy', 'Crime|Drama', 36.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (93, 'Yellow Handkerchief, The', 'Up-sized homogeneous groupware', 'Drama|Romance', 80.07);
insert into products (product_id, product_name, description, product_category, unit_price) values (94, 'Heartlands', 'De-engineered zero tolerance orchestration', 'Comedy|Drama', 43.87);
insert into products (product_id, product_name, description, product_category, unit_price) values (95, 'Sphere', 'Networked bandwidth-monitored approach', 'Sci-Fi|Thriller', 54.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (96, 'Line of Sight', 'Triple-buffered impactful process improvement', 'Documentary', 80.41);
insert into products (product_id, product_name, description, product_category, unit_price) values (97, 'Murder by Decree', 'Horizontal tangible database', 'Mystery|Thriller', 71.99);
insert into products (product_id, product_name, description, product_category, unit_price) values (98, 'Holiday in Handcuffs', 'Robust client-server contingency', 'Comedy|Romance', 58.12);
insert into products (product_id, product_name, description, product_category, unit_price) values (99, 'Remember the Night', 'Synergistic background open system', 'Comedy|Drama|Romance', 12.39);
insert into products (product_id, product_name, description, product_category, unit_price) values (100, 'Clink of Ice, The (a.k.a.: Sound of Ice Cubes, The) (Le bruit des glaçons)', 'Synchronised multi-tasking methodology', 'Comedy|Drama', 57.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (101, 'Generation Um...', 'Extended logistical application', 'Drama', 80.07);
insert into products (product_id, product_name, description, product_category, unit_price) values (102, 'Rebirth of Mothra III', 'Cross-platform coherent model', 'Action|Fantasy|Sci-Fi', 24.86);
insert into products (product_id, product_name, description, product_category, unit_price) values (103, 'Baton Rouge (Bâton rouge)', 'Object-based object-oriented policy', 'Thriller', 84.91);
insert into products (product_id, product_name, description, product_category, unit_price) values (104, 'Fallen Angels (Duo luo tian shi)', 'Open-source zero administration Graphical User Interface', 'Drama|Romance', 81.76);
insert into products (product_id, product_name, description, product_category, unit_price) values (105, 'Mujhse Dosti Karoge!', 'Front-line didactic approach', 'Drama|Romance', 94.02);
insert into products (product_id, product_name, description, product_category, unit_price) values (106, 'Ghosts of Cité Soleil', 'Balanced value-added approach', 'Action|Documentary|Drama|Romance|War', 54.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (107, 'The Chumscrubber', 'Seamless client-driven concept', 'Comedy|Drama', 40.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (108, 'Adventures of Mark Twain, The', 'Implemented background strategy', 'Adventure|Drama', 57.79);
insert into products (product_id, product_name, description, product_category, unit_price) values (109, 'Wings of Honneamise (Ôritsu uchûgun Oneamisu no tsubasa)', 'Virtual high-level throughput', 'Animation|Drama|Sci-Fi|War', 47.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (110, 'Extreme Ops', 'Horizontal zero tolerance focus group', 'Action|Adventure|Crime|Thriller', 17.5);
insert into products (product_id, product_name, description, product_category, unit_price) values (111, 'Gorilla at Large', 'Total multi-tasking complexity', 'Mystery|Thriller', 14.89);
insert into products (product_id, product_name, description, product_category, unit_price) values (112, 'Rage of Angels: The Story Continues', 'Optional bifurcated database', 'Drama', 19.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (113, 'I Walk the Line', 'Innovative motivating superstructure', 'Drama', 93.78);
insert into products (product_id, product_name, description, product_category, unit_price) values (114, 'Parking (Ting che)', 'Enterprise-wide systematic task-force', 'Crime|Drama', 84.0);
insert into products (product_id, product_name, description, product_category, unit_price) values (115, 'Do You Like Hitchcock? (Ti piace Hitchcock?)', 'Customizable high-level workforce', 'Horror|Mystery|Thriller', 72.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (116, 'Crimewave', 'Integrated encompassing infrastructure', 'Comedy|Crime', 81.46);
insert into products (product_id, product_name, description, product_category, unit_price) values (117, 'Burma VJ: Reporting from a Closed Country (Burma VJ: Reporter i et lukket land)', 'User-friendly leading edge methodology', 'Documentary', 86.33);
insert into products (product_id, product_name, description, product_category, unit_price) values (118, 'Sebastiane', 'Decentralized client-server capacity', 'Drama|Thriller', 78.59);
insert into products (product_id, product_name, description, product_category, unit_price) values (119, 'Sam''s Song', 'Visionary secondary archive', 'Drama', 90.89);
insert into products (product_id, product_name, description, product_category, unit_price) values (120, 'Forgotten, The', 'Synchronised dynamic synergy', 'Drama|Mystery|Sci-Fi|Thriller', 17.07);
insert into products (product_id, product_name, description, product_category, unit_price) values (121, 'Follow Me Quietly', 'Assimilated bandwidth-monitored architecture', 'Crime|Drama|Film-Noir|Mystery', 96.14);
insert into products (product_id, product_name, description, product_category, unit_price) values (122, 'Adjust Your Tracking', 'Decentralized methodical flexibility', 'Documentary', 24.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (123, 'Whipped', 'Synergized client-driven model', 'Comedy', 72.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (124, 'Fear No Evil', 'Organized mission-critical definition', 'Horror', 77.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (125, 'Capricious Summer (Rozmarné léto)', 'Implemented zero tolerance standardization', 'Comedy', 97.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (126, 'Field in England, A', 'Total static flexibility', 'Drama|Fantasy|Thriller|War', 35.74);
insert into products (product_id, product_name, description, product_category, unit_price) values (127, 'Adult World', 'Open-source discrete database', 'Comedy', 71.09);
insert into products (product_id, product_name, description, product_category, unit_price) values (128, 'Riptide', 'Synchronised stable structure', 'Drama', 96.84);
insert into products (product_id, product_name, description, product_category, unit_price) values (129, 'Crazy Horse', 'Profound maximized collaboration', 'Documentary', 98.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (130, 'Dead or Alive 2: Tôbôsha', 'Multi-lateral bandwidth-monitored portal', 'Action|Crime|Thriller', 53.13);
insert into products (product_id, product_name, description, product_category, unit_price) values (131, 'Wichita', 'Organic executive conglomeration', 'Action|Romance|Western', 64.86);
insert into products (product_id, product_name, description, product_category, unit_price) values (132, 'Deadly Mantis, The', 'Innovative zero administration portal', 'Horror|Sci-Fi', 90.64);
insert into products (product_id, product_name, description, product_category, unit_price) values (133, 'Hothead (Coup de tête)', 'Ergonomic logistical support', 'Comedy|Drama', 40.34);
insert into products (product_id, product_name, description, product_category, unit_price) values (134, 'Valley Girl', 'Cross-platform next generation contingency', 'Comedy|Romance', 48.17);
insert into products (product_id, product_name, description, product_category, unit_price) values (135, 'Iria: Zeiram the Animation ', 'Cross-platform mobile methodology', 'Action|Animation|Horror|Sci-Fi|Thriller', 5.53);
insert into products (product_id, product_name, description, product_category, unit_price) values (136, 'Misérables, Les', 'Cloned foreground projection', 'Drama', 10.46);
insert into products (product_id, product_name, description, product_category, unit_price) values (137, 'Love Nest, The', 'Business-focused dedicated methodology', 'Comedy', 17.32);
insert into products (product_id, product_name, description, product_category, unit_price) values (138, 'Move (3 Zimmer/Küche/Bad)', 'Universal needs-based functionalities', 'Comedy|Drama', 44.52);
insert into products (product_id, product_name, description, product_category, unit_price) values (139, 'Hudson Hawk', 'Customer-focused grid-enabled neural-net', 'Action|Adventure|Comedy', 49.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (140, 'Management', 'Proactive tertiary implementation', 'Comedy|Romance', 20.41);
insert into products (product_id, product_name, description, product_category, unit_price) values (141, 'Pretty Good for a Human (People Not as Bad as They Seem) (Aika hyvä ihmiseksi)', 'Fundamental cohesive workforce', 'Comedy|Drama', 94.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (142, 'Freeloaders', 'Integrated 4th generation concept', 'Comedy', 77.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (143, 'Ladies and Gentlemen, the Fabulous Stains (a.k.a. All Washed Up)', 'Multi-tiered modular toolset', 'Comedy|Drama', 8.45);
insert into products (product_id, product_name, description, product_category, unit_price) values (144, 'The Pumaman', 'Balanced multi-state superstructure', 'Action|Adventure|Fantasy|Sci-Fi', 77.16);
insert into products (product_id, product_name, description, product_category, unit_price) values (145, 'Charlie Chan Carries On', 'De-engineered demand-driven secured line', 'Mystery', 44.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (146, 'Adventures of Huckleberry Finn, The', 'Sharable regional neural-net', 'Adventure|Drama', 54.43);
insert into products (product_id, product_name, description, product_category, unit_price) values (147, 'Heavenly Body, The', 'Streamlined leading edge architecture', 'Comedy|Romance', 26.55);
insert into products (product_id, product_name, description, product_category, unit_price) values (148, 'Hoodoo Ann', 'Implemented zero defect middleware', 'Comedy|Drama|Romance', 87.21);
insert into products (product_id, product_name, description, product_category, unit_price) values (149, 'Dragon Seed', 'Optional user-facing productivity', 'Drama', 12.76);
insert into products (product_id, product_name, description, product_category, unit_price) values (150, 'National Gallery', 'Profit-focused client-driven function', 'Documentary', 35.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (151, 'In Order of Disappearance (Kraftidioten)', 'Innovative bi-directional focus group', 'Action|Comedy|Crime|Thriller', 51.05);
insert into products (product_id, product_name, description, product_category, unit_price) values (152, 'Philanthropy (Filantropica)', 'Triple-buffered maximized parallelism', 'Comedy', 28.61);
insert into products (product_id, product_name, description, product_category, unit_price) values (153, 'River''s Edge', 'Integrated full-range pricing structure', 'Crime|Drama', 14.22);
insert into products (product_id, product_name, description, product_category, unit_price) values (154, 'Big River Man', 'Decentralized human-resource portal', 'Documentary', 34.33);
insert into products (product_id, product_name, description, product_category, unit_price) values (155, 'Tomb of Ligeia, The', 'Ameliorated optimizing installation', 'Horror', 57.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (156, 'Big Eyes', 'Diverse empowering hierarchy', 'Drama', 53.82);
insert into products (product_id, product_name, description, product_category, unit_price) values (157, '13 Lakes', 'User-centric transitional archive', 'Documentary', 26.42);
insert into products (product_id, product_name, description, product_category, unit_price) values (158, 'Far from Home', 'Down-sized object-oriented challenge', 'Thriller', 17.98);
insert into products (product_id, product_name, description, product_category, unit_price) values (159, 'Three Colors: Blue (Trois couleurs: Bleu)', 'Optional exuding archive', 'Drama', 73.73);
insert into products (product_id, product_name, description, product_category, unit_price) values (160, 'After Five in the Jungle (Nach Fünf im Urwald)', 'Persistent 3rd generation parallelism', 'Comedy|Romance', 41.57);
insert into products (product_id, product_name, description, product_category, unit_price) values (161, 'Berserk: The Golden Age Arc 3 - Descent', 'Ameliorated impactful middleware', 'Action|Animation|Fantasy', 35.47);
insert into products (product_id, product_name, description, product_category, unit_price) values (162, 'Repo Men', 'Expanded cohesive matrices', 'Action|Sci-Fi|Thriller', 12.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (163, 'Léolo', 'Persevering leading edge success', 'Comedy|Drama', 23.44);
insert into products (product_id, product_name, description, product_category, unit_price) values (164, 'Carcasses', 'Multi-tiered logistical software', 'Documentary', 89.13);
insert into products (product_id, product_name, description, product_category, unit_price) values (165, 'Alabama Moon', 'Managed global Graphic Interface', 'Adventure|Children|Drama', 65.58);
insert into products (product_id, product_name, description, product_category, unit_price) values (166, 'Hothead (Coup de tête)', 'Universal mission-critical time-frame', 'Comedy|Drama', 24.68);
insert into products (product_id, product_name, description, product_category, unit_price) values (167, 'Diary of a Wimpy Kid: Dog Days', 'Polarised exuding application', 'Children|Comedy', 77.54);
insert into products (product_id, product_name, description, product_category, unit_price) values (168, 'Uprise', 'Function-based secondary monitoring', 'Drama', 24.56);
insert into products (product_id, product_name, description, product_category, unit_price) values (169, 'Associate, The (Associé, L'')', 'Centralized contextually-based productivity', 'Comedy', 25.5);
insert into products (product_id, product_name, description, product_category, unit_price) values (170, 'Ten Little Indians (Ein Unbekannter rechnet ab) (And Then There Were None)', 'Triple-buffered dedicated Graphical User Interface', 'Crime|Drama|Mystery', 43.45);
insert into products (product_id, product_name, description, product_category, unit_price) values (171, 'Phenomena (a.k.a. Creepers)', 'Reactive radical encryption', 'Horror|Mystery|Thriller', 80.38);
insert into products (product_id, product_name, description, product_category, unit_price) values (172, 'Uncle Nino', 'Team-oriented 24 hour matrices', 'Comedy', 31.93);
insert into products (product_id, product_name, description, product_category, unit_price) values (173, 'Broadway Melody of 1938', 'Robust heuristic framework', 'Musical|Romance', 31.45);
insert into products (product_id, product_name, description, product_category, unit_price) values (174, 'Fine Madness, A', 'Assimilated multimedia process improvement', 'Comedy|Drama|Romance', 39.8);
insert into products (product_id, product_name, description, product_category, unit_price) values (175, 'Frozen City (Valkoinen kaupunki) ', 'Inverse asynchronous frame', 'Drama', 50.76);
insert into products (product_id, product_name, description, product_category, unit_price) values (176, 'Delicate Balance, A', 'Horizontal bandwidth-monitored matrix', 'Drama', 85.69);
insert into products (product_id, product_name, description, product_category, unit_price) values (177, 'Baby Boy', 'Programmable optimal analyzer', 'Crime|Drama', 64.96);
insert into products (product_id, product_name, description, product_category, unit_price) values (178, 'Construction, The (En construcción)', 'Realigned clear-thinking instruction set', 'Documentary', 42.52);
insert into products (product_id, product_name, description, product_category, unit_price) values (179, 'Wrestling (Bræðrabylta)', 'Networked eco-centric project', 'Drama|Romance', 21.53);
insert into products (product_id, product_name, description, product_category, unit_price) values (180, 'A Via Láctea', 'Open-source client-driven emulation', 'Drama', 27.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (181, 'Hollywood or Bust', 'Monitored systemic orchestration', 'Comedy|Musical', 14.56);
insert into products (product_id, product_name, description, product_category, unit_price) values (182, 'Big Day, The (We Met on the Vineyard)', 'Synergized hybrid frame', 'Comedy', 78.94);
insert into products (product_id, product_name, description, product_category, unit_price) values (183, 'Return from Witch Mountain', 'Multi-lateral radical circuit', 'Children|Sci-Fi', 62.17);
insert into products (product_id, product_name, description, product_category, unit_price) values (184, '2 Days in the Valley', 'Sharable grid-enabled knowledge user', 'Crime|Film-Noir', 17.09);
insert into products (product_id, product_name, description, product_category, unit_price) values (185, 'How to Train Your Dragon', 'Streamlined maximized product', 'Adventure|Animation|Children|Fantasy|IMAX', 19.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (186, 'Sleepwalking', 'Synergized 4th generation policy', 'Drama', 62.64);
insert into products (product_id, product_name, description, product_category, unit_price) values (187, 'Camp Rock 2: The Final Jam', 'Down-sized asymmetric emulation', 'Comedy|Musical|Romance', 42.12);
insert into products (product_id, product_name, description, product_category, unit_price) values (188, 'Strange Cargo', 'Upgradable bifurcated data-warehouse', 'Drama', 44.15);
insert into products (product_id, product_name, description, product_category, unit_price) values (189, 'Butter', 'User-centric fresh-thinking pricing structure', 'Comedy', 13.75);
insert into products (product_id, product_name, description, product_category, unit_price) values (190, 'Cradle of Fear', 'Total human-resource Graphic Interface', 'Crime|Drama|Horror|Mystery|Thriller', 90.71);
insert into products (product_id, product_name, description, product_category, unit_price) values (191, 'Whoregasm', 'Business-focused actuating attitude', '(no genres listed)', 24.95);
insert into products (product_id, product_name, description, product_category, unit_price) values (192, 'Milarepa', 'Stand-alone systemic orchestration', 'Action|Adventure|Drama', 73.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (193, 'Children of the Corn: Revelation', 'Devolved asymmetric forecast', 'Horror|Thriller', 88.04);
insert into products (product_id, product_name, description, product_category, unit_price) values (194, 'Steam', 'Realigned dedicated budgetary management', 'Comedy|Drama|Romance', 49.06);
insert into products (product_id, product_name, description, product_category, unit_price) values (195, 'Waking Life', 'Fully-configurable leading edge algorithm', 'Animation|Drama|Fantasy', 18.9);
insert into products (product_id, product_name, description, product_category, unit_price) values (196, 'The Casino Murder Case', 'Mandatory heuristic database', 'Action|Drama|Mystery', 48.66);
insert into products (product_id, product_name, description, product_category, unit_price) values (197, 'January Man, The', 'Digitized grid-enabled throughput', 'Comedy|Crime|Mystery|Thriller', 99.65);
insert into products (product_id, product_name, description, product_category, unit_price) values (198, 'Journeys with George', 'Fundamental exuding paradigm', 'Documentary', 65.59);
insert into products (product_id, product_name, description, product_category, unit_price) values (199, 'Mr. Kinky', 'Visionary discrete throughput', 'Comedy', 69.44);
insert into products (product_id, product_name, description, product_category, unit_price) values (200, '28 Weeks Later', 'Secured scalable Graphic Interface', 'Horror|Sci-Fi|Thriller', 83.4);
